### ISSUE TITLE
Add link to the gitbook to the repo settings

### ISSUE THREAD

**Issue by waldyrious** [Meta-Node/Aura-Docs#1]
This repository's metadata should contain a link to the rendered gitbook: https://brightid.gitbook.io/aura/ (similar to how https://github.com/BrightID/BrightID-Docs points to https://brightid.gitbook.io).

**Comment by adamstallard** [comment]
Is this what you mean?  (I just made this change)  
![image](https://user-images.githubusercontent.com/205792/220825986-9cc15099-720b-430f-85cc-2c34e5c054fc.png)

**Comment by waldyrious** [comment]
Yes, exactly! I never know how to call that field :sweat_smile:
